services: 
  db:
    image: postgres:latest
    restart: always
    ports: 
      - 8541:5432
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "pg"
      POSTGRES_DB: "test"
      POSTGRES_PASSWORD: "password"

volumes:
  db:
    driver: local