services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: test
    ports: 
      - 3306:3306
    volumes:
      - db:/var/lib/mysql

volumes:
  db:
    driver: local
